project:
  type: website

website:
  title: "Good practices for running workshops"
  favicon: icon-training.png

  sidebar:
    background: "#adbedd"
    search: true
    logo: icon-training.png
    pinned: true
    align: center

    repo-url: https://github.com/rstudio-conf-2022/workshop-good-practices
    repo-actions: [edit, issue]

    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - href: instructor.qmd
        text: Instructors
      - href: ta.qmd
        text: TAs

    page-footer:
      left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
      background: "#adbedd"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    toc: true

editor: visual

