---
title: "Recommendations for instructors"
number-sections: true
---

Our recommendations are as follows:

1.  [Reach out to your learners prior to the workshop]
2.  [Start with introductions]
3.  [Have learners use sticky notes for signaling]
4.  [Plan for interactivity]
5.  [Have a plan for two-way written communication]
6.  [Get feedback from learners]

Reach more about each of these below.

## Reach out to your learners prior to the workshop

Leading up to the workshop you're probably busy preparing your materials and this one is easy to slip through the cracks.
Make a note on your calendar to reach out to your learners at least one week prior to the workshop to give them a bit of information about what to expect as well as to communicate any expectations you might have for them.

-   You can communicate this information in an email or post on an RStudio Community thread and email the link to the thread. The latter has the benefit of receiving their follow-up questions on the thread so all participants can see the questions and answers, and it can save you some time from repeating the same answers in individual emails.
-   The pre-workshop communication can also include any setup instructions or any "homework" you want your learners to complete prior to the workshop, but you shouldn't on everyone completing them. Instead, make some time at the beginning of the workshop for folks to catch up with setup, or ask your TAs to help them as the learners arrive in the workshop room.
-   The marketing team can send any information to your workshop participants or you can request a list of participants' names and emails and reach out to them yourself.

## Start with introductions

This might sound obvious, but it's also each to forget when you're excited to jump right into the workshop material.
You should set aside 10-15 mins for introductions.

-   Start with introducing the teaching team -- each member of the teaching team (including TAs) should say their name and share at least one detail about themselves (e.g., where they're from, what they work on, etc.) briefly.
-   Then, give \~2 minutes for participants to introduce themselves to their neighbors. Ask them to share their name, where they're from, what they work on in 3 words or fewer, and name one thing they've made that they're proud of. The room will get loud, that's a good thing!
-   Wrap up the introduction by discussing the flow and communication strategy for the workshop. Make sure to let learners know how they can let you know when they're lost or stuck (e.g., "We'll use sticky notes to signal how the exercise is going").
-   [Read more about introductions here](https://github.com/tracykteal/instructors-introduction).

## Have learners use sticky notes for signaling

Hand out one pink and one green sticky to each of your learners.

-   During the exercises, learners should place a green sticky if they're done with the exercise and a pink sticky if they want help.
-   Learners can also use pink stickies anytime during the session to signal they're having trouble / are lost / would like help.
-   Remind your TAs to be on the lookout for stickies throughout the session. And if you see lots of pink stickies, that might be a good time to pause to get learners unstuck before continuing.

## Plan for interactivity

These will break up the monotony of a lecture and give learners a chance to work/discuss ideas with others in the session.
Some ideas are listed below.
There's no expectation that you would use all of these, in fact, you probably shouldn't!
Pick a few that feel right for your materials and your teaching style.

-   Polling / collecting questions: You can use [sli.do](sli.do) or similar for polling (multiple choice or open ended questions learners can respond to) and for live sharing of results. These tools can also be used to collect questions and for learners to upvote them.
-   Impromptu conversations: Encourage impromptu conversations between learners by ending exercises with "and share with your neighbor".
-   Think / pair / share: Pose a question, give some time for learners to think of on their own, then ask them to pair up with their neighbor and share their thoughts, and then ask each or some of the pairs to share their discussion with the whole class. [Read more about think / pair / share here](https://learninginnovation.duke.edu/blog/2017/08/fine-tuning-think-pair-share/).
-   Participatory live coding: For teaching code or workflows, particularly for longer segments, use [participatory live coding](https://carpentries.github.io/instructor-training/17-live.html). When doing so, an approach we recommend is I / we / you -- *I do it first. We do it together. You do it on your own*. [Read more about I / we / you here](https://classteaching.wordpress.com/2018/12/05/i-we-you-a-simple-approach-to-modelling/). [This blog post](https://yabellini.netlify.app/blog/2022_teaching_en/04-teaching/) also has fantastic tips for live coding, they're primarily for teaching online but many of them apply to in person teaching as well.

## Have a plan for two-way written communication

Sure, people can just raise their hands and ask a question, but sometimes you just need a place to copy-paste something that your learners can then copy-paste into their environment.
Some options are below.
Again, pick one that works for you!

-   GitHub Discussions: Each of your workshops have a GitHub repo, you can turn on GitHub Discussions on your repo and ask learners to put their questions there. You can similarly open a thread for random things you'll copy-paste throughout the workshop.
-   Slack / Discourse / etc. channel: You can create a Slack channel for your workshop for real-time communication. These platforms also have polling capabilities you could make use of.
-   [Hackmd](https://hackmd.io/) / [Etherpad](https://etherpad.org/) / Google Docs: These could be used for collaborative note-taking as well as a scratch pad for sharing notes, questions, pieces of code, etc.

## Get feedback from learners

-   During the workshop: Ask learners to provide feedback on the stickies twice a day; before lunch and at the end of the day.
    -   Give the learners one minute to write one positive thing on the green sticky note (e.g., one thing they've learned that they think will be useful), and one thing they found too fast, too slow, confusing, or irrelevant on the pink one.
        Learners can also use the pink sticky note for questions that haven't yet been answered.

    -   Review them during the break or overnight and start the subsequent module with a brief summary and any clarifications that might help the learners.

    -   [Read more about minute cards here](http://swcarpentry.github.io/swc-releases/2017.02/instructor-training/15-practices/).
-   You can also create and use your own pre/post workshop surveys:
    -   Pre-workshop survey: To find out what your learners are most interested in learning about
    -   Post-workshop survey: To find out what they learned and what could be improved. Note that we will also run a general post-workshop survey and share with you aggregate quantitative data on the workshops overall.
    -   As mentioned earlier, the marketing team can send these to your workshop participants or you can request a list of participants' names and emails and reach out to them yourself.
