---
title: "Recommendations for TAs"
---

Your primary role as a teaching assistance (TA) is to help individual learners throughout the workshop -- help troubleshoot, help them find their place in the lesson, etc.
Here are a few tips to help you with this role:

-   Watch out for sticky notes on learners' laptops throughout the lesson.
-   Give space for the learners to ask questions to the instructor, save questions that you have for later.
-   Resist the urge to touch learners' keyboards, instead guide them to the solution verbally. If you want to show how to do a specific thing, you can bring your own laptop along and demonstrate there.
-   Be kind and don't express surprise if someone doesn't know something already.
-   Use inclusive language and don't use the word "just", e.g., "do X" instead of "just do X"
-   You don't need to know everything. Don't hesitate to ask other TAs to help or say "it's a question for the instructor later".
-   If the same question is asked by many learners, let the instructor know.
